export const musics = [
    {audio: '/assets/music/crystal.mp3', Image: 'https://i.ytimg.com/vi/T5Pvq3Cj6eQ/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLASEjG1pq2pqqx67cGU2Hz2h0EJHA', name : 'Chrystal - The Days (NOTION Remix) (slowed tiktok version) (TRADUÇÃO/LEGENDADO) PT-BR'},
    {audio: '/assets/music/prank.mp3', Image: 'https://i.ytimg.com/vi/DRh2AmHFnYs/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDQMBs3S31FFRZFZIJzl0uh9dDuAA', name : 'Lil Zé - Prank (Official Music Vídeo)'},
    {audio: '/assets/music/Som.mp3', Image: 'https://i.ytimg.com/vi/T-h3O3djG9U/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBVsCd50ut4izuf6v0jivlfFQYu8Q', name : 'Matuê - O Som'},
    {audio: '/assets/music/amado.mp3', Image: 'https://i.ytimg.com/vi/_CK4O1_Bvxg/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBVsCd50ut4izuf6v0jivlfFQYu8Q', name : 'Vanessa Da Mata - Amado (Ao Vivo)'},
    {audio: '/assets/music/amor_puro.mp3', Image: 'https://i.ytimg.com/vi/Af7ieNv0wXY/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBVsCd50ut4izuf6v0jivlfFQYu8Q', name : 'Djavan - Um Amor Puro (Áudio Oficial)'},
    {audio: '/assets/music/vaidade.mp3', Image: 'https://i.ytimg.com/vi/QwNXB_SF6rw/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAAa9D6ajXo_7P_G0pSfeJsc0qVlA', name : 'Djavan - Flor Do Medo (Vaidade) [Áudio Oficial]'},
    {audio: '/assets/music/every_breath_you_take.mp3', Image: 'https://i.ytimg.com/vi/OMOGaugKpzs/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAv_Lf4P43RdqKSjfVD3Zx8mVDBWw', name : 'The Police - Every Breath You Take (Official Music Video)'},     
    {audio: '/assets/music/feel_it.mp3', Image: 'https://i.ytimg.com/vi/11rpGprITo0/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC2PKPu4vZSJoJPMogvzWHprJJAsA', name : 'd4vd - Feel It (Animated Lyric Video)'},
    {audio: '/assets/music/oceano.mp3', Image: 'https://i.ytimg.com/vi/2kqdlAYNEzk/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCKbEUW2pv1iW5v9FLXbX0Z7rjCBw', name : 'Djavan - Oceano (Ao Vivo)'},
    {audio: '/assets/music/outra_vida.mp3', Image: 'https://i.ytimg.com/vi/6BaCNYU2YR0/hqdefault.jpg?sqp=-oaymwFBCPYBEIoBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGGUgTihIMA8=&rs=AOn4CLArP9t82onY6zuzSPAxxdXEQ0rnyA', name : 'Armandinho - Outra Vida (Acústico) | Vídeo Oficial'},
];